version: "3.3"
services:
  mysql:
    image: mysql:5.7.27
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: etsiinfbot

    command: "--character-set-server=utf8mb4 --skip-character-set-client-handshake=1"

    restart: "on-failure"

  etsiinfbot:
    build:
      context: ./etsiinfbot-docker
      args:
        github_api_token: ${GITHUB_API_TOKEN}

    environment:
      DB_HOST: mysql
      DB_NAME: etsiinfbot
      DB_USER: root
      DB_PASS: abc123

    volumes:
      - "./params.php:/sources/config/params.php"

    env_file:
      - ./bot.env

    depends_on:
      - mysql

    restart: "on-failure"

volumes:
  db-data:
